name: Workflow2

on: pull_request

jobs:
  validar2:
    runs-on: ubuntu-latest
    permissions:
     security-events: write
    steps:
      - name: Calidad de codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
            linter: pylint
      
